### ISSUE TITLE
Small typo in text

### ISSUE THREAD

**Issue by martinamorris** [statnet/tergm#10]
In: https://github.com/statnet/tergm/blob/e6713ce59099babfe3c9505ab7d1ac0a0dc599ca/R/stergm.getMCMCsample.R#L60

This should be model.diss, yes?  I'm happy to change, but wanted to make sure

**Comment by krivit** [comment]
Those are old comments that we should probably just get rid of, since the information is now in Roxygen form. However, the corresponding line in the Roxygen documentation appears to have the same error:
https://github.com/statnet/tergm/blob/e6713ce59099babfe3c9505ab7d1ac0a0dc599ca/R/stergm.getMCMCsample.R#L112-L113

That should be fixed.

**Comment by martinamorris** [comment]
I'm happy to fix it, just want to make sure the fix is: change `statsmatrix.diss` to `statsmatrix.form`

**Comment by krivit** [comment]
Belatedly yes, that is the fix. :-)

**Comment by martinamorris** [comment]
should the update in tergm-private go into master or dev?

**Comment by krivit** [comment]
`master`. It can then be merged into `dev` if necessary.
