### ISSUE TITLE
Outsource tergm CMLE facilities to ergm.multi as much as practical.

### ISSUE THREAD

**Issue by krivit** [statnet/tergm#103]
Block-diagonal matrix construction and deconstruction and other facilities can live in `ergm.multi`, with `tergm` handling only the temporal components. Other than avoiding code duplication, an added advantage of this is that by piggybacking on `N()` operator, it would be possible to have TERGMs with time-varying network-level covariates, so that, say `Form(~edges, ~factor(.Time))` would fit a different formation effect for each time step. I've prototyped it in `statnet/ergm.multi@for-tergm` and `statnet/tergm@from-multi` branches.

I think most of @statnet/epimodel uses the EGMME facilities, so they shouldn't be affected. Is that right?

**Comment by AdrienLeGuillou** [comment]
Hi @krivit, what do you mean by EGMME facilities? (sorry I am only slowly getting into the `statnet` parts of EpiModel)

**Comment by martinamorris** [comment]
Adrien --  EGMME = Equilibrium generalized method of moments estimation

That refers to the estimation methods/code used when the network data being
used are a single egocentric sample of a network, or provided as a vector
of target stats.  In both cases the network statistics are observed at a
single timepoint, and a temporal ERGM estimate can only be obtained by
making the assumption that the system is in equilibrium (b/c we don't have
any info on how it is changing).  We typically use the ED approximation to
further simplify estimation (we subtract the dissolution coef estimates
from the ergm coefs to get the formation coefs).

The alternative is CMLE (conditional MLE), which is used when you have
panels of complete network data.

Pavel am I right in assuming that what you're talking about requires CMLE?

**Comment by CarterButts** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Seems like a good idea to me - put the core code in one place, and let application-specific code ride in the special purpose packages...Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: ***@***.***: November 28, 2022 2:28 AMTo: ***@***.***: ***@***.***: ***@***.***: [statnet/tergm] Outsource tergm CMLE facilities to ergm.multi as much as practical. (Issue #103)  
Block-diagonal matrix construction and deconstruction and other facilities can live in ergm.multi, with tergm handling only the temporal components. Other than avoiding code duplication, an added advantage of this is that by piggybacking on N() operator, it would be possible to have TERGMs with time-varying network-level covariates, so that, say Form(~edges, ~factor(.Time)) would fit a different formation effect for each time step. I've prototyped it in ***@***.*** and ***@***.*** branches.
I think most of @statnet/epimodel uses the EGMME facilities, so they shouldn't be affected. Is that right?

**Comment by krivit** [comment]
OK. I'll make the changes in the `ergm.multi` API needed by `tergm` before pushing it to CRAN.

**Comment by krivit** [comment]
Done.
